settingdata={
    "first":[
        {
           "headImg":"hello",
           "name":"微微",
           "weixin_id":"zhl4520684",
           "erweima_img":"",
           "unique_id":"head_id"
        }
    ],
    "second":[
        {
           "headImg":require('../images/qianbao.png'),
           "name":"钱包",
           "unique_id":"head_qianbao"
        }
    ],
    "third":[
        {
            "headImg":require("../images/shoucang.png"),
            "name":"收藏",
            "unique_id":"head_shoucang"
         },
         {
            "headImg":require("../images/xiangce.png"),
            "name":"相册",
            "unique_id":"head_xiangce"
         }, 
         {
            "headImg":require("../images/kabao.png"),
            "name":"卡包",
            "unique_id":"head_kabao"
         },
         {
            "headImg":require("../images/biaoqing.png"),
            "name":"表情",
            "unique_id":"head_biaoqing"
         }
    ],
    "four":[
        {
            "headImg":require("../images/shezhi.png"),
            "name":"设置",
            "unique_id":"head_set"
         }
    ]
}
export default settingdata;